name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Run check, linter
        run: |
          uv sync --locked --all-extras --dev
          uvx ruff check .
          uvx ruff format . --check

      - name: Run E2E tests
        run: |
          uvx pytest -v --log-cli-level=INFO -s
